apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp
  labels:
    app: goapp
spec:
  replicas: 1  # Number of replicas
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: goapp
        image: hiteshreeruparell/demo:goapp  # Replace with your Docker Hub username and image tag
        ports:
        - containerPort: 8080  # Port your Go application listens on
        env:
        - name: ENVIRONMENT
          value: "production"  # Example environment variable
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
