apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-docker-deployment
  labels:
    app: go-docker
spec:
  replicas: 1  # Number of replicas
  selector:
    matchLabels:
      app: go-docker
  template:
    metadata:
      labels:
        app: go-docker
    spec:
      containers:
      - name: go-docker-container
        image: justynroberts/go-app:latest  # Replace with your Docker Hub username and image tag
        ports:
        - containerPort: 8080  # Port your Go application listens on
        env:
        - name: ENVIRONMENT
          value: "production"  # Example environment variable
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
